name: "running unit test, build docker image"
on: 
  push:
    branches:
      - "main"
jobs:
  unit-test:
    name: "unit test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: running unit test
        run: go test ./... -cover
  
